# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
  skip-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  go: '1.21'

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
  revive:
    rules:
      - name: exported
        disabled: true
  gofumpt:
    module-path: github.com/Bdido86/chat-server
    extra-rules: true
 
linters:
  enable-all: true
  disable:
    - varcheck
    - nosnakecase
    - interfacer
    - ifshort
    - scopelint
    - deadcode
    - exhaustivestruct
    - maligned
    - golint
    - structcheck
    - depguard
    - gci
    - godot
    - exhaustruct
    - godox
    - goimports

issues:
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
